import JSZip from "jszip";
import { saveAs } from "file-saver";

type FlowJSON = {
    nodes: { id: string; label: string; type: string }[];
    edges: { from: string; to: string; label: string }[];
};

function toFileName(name: string) {
    return name.toLowerCase().replace(/\s+/g, "-");
}

function toComponentName(name: string) {
    return name.replace(/\s+/g, "");
}

export async function generateProject(flow: FlowJSON) {
    const zip = new JSZip();

    const project = zip.folder("project");
    const frontend = project?.folder("frontend");
    const backend = project?.folder("backend");
    const app = frontend?.folder("app");

    if (!flow.nodes.length) {
        alert("Add at least one node!");
        return;
    }

    // ------------------------
    // FRONTEND (SCREENS)
    // ------------------------
    flow.nodes
        .filter((n) => n.type === "screen")
        .forEach((screen) => {
            const fileName = `${toFileName(screen.label)}.tsx`;

            const content = `
export default function ${toComponentName(screen.label)}() {
  return <div>${screen.label} Screen</div>;
}
      `;

            app?.file(fileName, content);
        });

    // ------------------------
    // BACKEND (EVENTS)
    // ------------------------
    let routes = "";

    flow.nodes
        .filter((n) => n.type === "event")
        .forEach((event) => {
            const routeName = event.label.toLowerCase();

            routes += `
@app.get("/${routeName}")
def ${routeName}():
    return {"message": "${event.label} endpoint"}
`;
        });

    const mainPy = `
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def root():
    return {"message": "Hello from Flowboard"}

${routes}
`;

    backend?.file("main.py", mainPy);

    // ------------------------
    // PACKAGE.JSON
    // ------------------------
    frontend?.file(
        "package.json",
        JSON.stringify(
            {
                name: "flowboard-app",
                version: "1.0.0",
                scripts: {
                    dev: "next dev",
                },
            },
            null,
            2
        )
    );

    // ------------------------
    // REQUIREMENTS
    // ------------------------
    backend?.file(
        "requirements.txt",
        `
fastapi
uvicorn
`
    );

    // ------------------------
    // README
    // ------------------------
    const screens = flow.nodes
        .filter((n) => n.type === "screen")
        .map((n) => n.label)
        .join(", ");

    const readme = `
# 🚀 Generated by Flowboard

This project was auto-generated from a visual flow.

## 🧩 Screens
${screens}

## ⚙️ Setup

### Frontend
cd frontend
npm install
npm run dev

### Backend
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
`;

    project?.file("README.md", readme);

    // ------------------------
    // DOWNLOAD ZIP
    // ------------------------
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, "flowboard-project.zip");
}

